### ISSUE TITLE
Gun Game maps missing

### ISSUE THREAD

**Issue by davidoskky** [Shtoyan/temp#1]
I looked through my server files and found a bunch of gun game maps you didn't list.
I have no idea where they come from or who's the author, except for staircase which is by Mastrocoltello.

I zipped all the rom files together, but didn't check each of them.
Check if some special texture is required, if that's the case I'll go find it in my server files.

https://www.mediafire.com/file/0xk4p8dru474boj/missingMaps.zip/file

**Comment by davidoskky** [comment]
My mistake, this is the map by Mastrocoltello
https://www.mediafire.com/file/sh0wkoii2fs3oos/Platform.zip/file
Textures: https://www.mediafire.com/file/76oyurywuypo7nc/Custom_modular.zip/file

**Comment by Shtoyan** [comment]
Thanks a lot! I need some time to set the server again and add new map entries, will inform you at the end.

**Comment by Shtoyan** [comment]
@davidoskky I need few packages:

- `dotd`.
- `paredes`.
- `bfparedes`.

```cpp
Warning: Failed to load 'dotd': Can't find file for package 'dotd'
Warning: Failed to load 'GG-Ponte': Can't find file for package 'dotd'
Warning: Failed to load 'LevelSummary GG-Ponte.LevelSummary': Can't find file for package 'dotd'
Warning: Error loading GG-Ponte !

Warning: Failed to load 'dotd': Can't find file for package 'dotd'
Warning: Failed to load 'GG-Octogono': Can't find file for package 'dotd'
Warning: Failed to load 'LevelSummary GG-Octogono.LevelSummary': Can't find file for package 'dotd'
Warning: Error loading GG-Octogono !

Warning: Failed to load 'dotd': Can't find file for package 'dotd'
Warning: Failed to load 'GG-NoshahrCanals': Can't find file for package 'dotd'
Warning: Failed to load 'LevelSummary GG-NoshahrCanals.LevelSummary': Can't find file for package 'dotd'
Warning: Error loading GG-NoshahrCanals !

Warning: Failed to load 'dotd': Can't find file for package 'dotd'
Warning: Failed to load 'GG-Hangar': Can't find file for package 'dotd'
Warning: Failed to load 'LevelSummary GG-Hangar.LevelSummary': Can't find file for package 'dotd'
Warning: Error loading GG-Hangar !

Warning: Failed to load 'dotd': Can't find file for package 'dotd'
Warning: Failed to load 'GG-Encruzilhada': Can't find file for package 'dotd'
Warning: Failed to load 'LevelSummary GG-Encruzilhada.LevelSummary': Can't find file for package 'dotd'
Warning: Error loading GG-Encruzilhada !

Warning: Failed to load 'paredes': Can't find file for package 'paredes'
Warning: Failed to load 'GG-Combat': Can't find file for package 'paredes'
Warning: Failed to load 'LevelSummary GG-Combat.LevelSummary': Can't find file for package 'paredes'
Warning: Error loading GG-Combat !

Warning: Failed to load 'bfparedes': Can't find file for package 'bfparedes'
Warning: Failed to load 'GG-BF3metro': Can't find file for package 'bfparedes'
Warning: Failed to load 'LevelSummary GG-BF3metro.LevelSummary': Can't find file for package 'bfparedes'
Warning: Error loading GG-BF3metro !
```

**Comment by davidoskky** [comment]
Alright, I think these should be all of them.
https://www.mediafire.com/file/tsen9jfzwwc85zw/textures.zip/file

**Comment by Shtoyan** [comment]
There are still missing files with these 2 maps..

```cpp
Warning: Failed to load 'chao': Can't find file for package 'chao'
Warning: Failed to load 'GG-Combat': Can't find file for package 'chao'

Warning: Failed to load 'bfpisocolonial': Can't find file for package 'bfpisocolonial'
Warning: Failed to load 'GG-BF3metro': Can't find file for package 'bfpisocolonial'
```

Other maps have been added to the map list: https://github.com/InsultingPros/KFStory/commit/f96d9665c374a499a9ec18251355e9b62e76eda8, https://github.com/InsultingPros/KFStory/commit/842630fb556567834b8ed109b021ce210eecec7c

**Comment by davidoskky** [comment]
Great, here are the missing textures
http://www.mediafire.com/file/7o8wqaurfdi0omg/textures.zip

**Comment by Shtoyan** [comment]
GG-BF3Metro added: https://github.com/InsultingPros/KFStory/commit/4ecafce32374bade540c788829596be7c235a1db

GG-Combat still has missing files:

```cpp
Failed to load 'terra': Can't find file for package 'terra'
Failed to load 'GG-Combat': Can't find file for package 'terra'
```

**Comment by davidoskky** [comment]
Here https://www.mediafire.com/file/g3w5ynusqpa4v0n/terra.utx/file

**Comment by Shtoyan** [comment]
Everything is done: https://github.com/InsultingPros/KFStory/commit/aef3f2901588a9500bc2d751ad24ad35cfb1d594

Thanks again.
